[workspace]
members = [
	'node',
	'pallets/*',
	'runtime/manta',
	'runtime/calamari',
]

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
opt-level = 3
codegen-units = 1
debug = false

[profile.test]
debug = true
