[package]
authors = ['Manta Network']
name = "manta-vesting"
version = "3.0.6"
edition = "2018"
homepage = 'https://manta.network'
license = 'GPL-3.0'
repository = 'https://github.com/Manta-Network/Manta/'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.1", default-features = false, features = ["derive"] }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', default-features = false, optional = true, branch = "polkadot-v0.9.11" }
frame-support = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.11" }
frame-system = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.11" }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.11" }
sp-std = { git = 'https://github.com/paritytech/substrate.git', default-features = false, branch = "polkadot-v0.9.11" }

[dev-dependencies]
hex-literal = "0.3.3"
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.11" }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.11" }
sp-io = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.11" }
sp-storage = { git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.11" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
    "scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
