[package]
authors = ['Manta Network']
name = "manta-primitives"
version = "3.0.1"
edition = "2018"
homepage = 'https://manta.network'
license = 'GPL-3.0'
repository = 'https://github.com/Manta-Network/Manta/'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.1.0", default-features = false }
smallvec = "1.6.1"

# Substrate primitives
sp-consensus-aura = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }
sp-core = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }
sp-std = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }
sp-io = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }
sp-runtime = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }

# Substrate frames
frame-support = { git = 'https://github.com/purestake/substrate.git', default-features = false, branch = "crystalin-v0.9.9-block-response-length" }

[features]
default = ["std"]
std = [
	'codec/std',
	'frame-support/std',
	'sp-consensus-aura/std',
	'sp-io/std',
	'sp-std/std',
]
