---

# yamllint disable rule:line-length

name: publish deb/rpm packages
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - deb-rpm
  release:
    types:
      - published
jobs:
  sync-repo-bucket:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        repo:
          -
            name: deb.manta.systems
            generator:
              package: reprepro
              command: reprepro
              config:
                source: https://raw.githubusercontent.com/Manta-Network/Manta/deb-rpm/scripts/package/deb-maintainer-scripts/distributions
                target: conf/distributions
          -
            name: rpm.manta.systems
            generator:
              package: createrepo-c
              command: createrepo_c
    steps:
      -
        name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y pass
          sudo apt-get install -y expect
          sudo apt-get install -y gpg
          sudo apt-get install -y ${{ matrix.repo.generator.package }}

          pip3 install awscli --upgrade --user
          pip3 install yq --upgrade --user

          sudo mkdir -p /usr/local/bin
          sudo curl -sL -o /usr/local/bin/discord https://raw.githubusercontent.com/ChaoticWeg/discord.sh/59cab0c/discord.sh
          sudo chmod +x /usr/local/bin/discord

          
      -
        name: configure aws
        run: |
          mkdir -p ${HOME}/.aws
          echo [pelagos] >> ${HOME}/.aws/credentials
          echo aws_access_key_id = ${{ secrets.OPS_AWS_ACCESS_KEY_ID }} >> ${HOME}/.aws/credentials
          echo aws_secret_access_key = ${{ secrets.OPS_AWS_SECRET_ACCESS_KEY }} >> ${HOME}/.aws/credentials
      -
        run: |
          if ! aws s3api head-bucket \
            --profile pelagos \
            --region eu-central-1 \
            --bucket ${{ matrix.repo.name }} \
            2> /dev/null; then
            aws s3api create-bucket \
              --profile pelagos \
              --region eu-central-1 \
              --bucket ${{ matrix.repo.name }} \
              --acl public-read \
              --create-bucket-configuration LocationConstraint=eu-central-1
          fi
          aws s3 sync \
            --profile pelagos \
            --region eu-central-1 \
            s3://${{ matrix.repo.name }} \
            ${{ github.workspace }}/${{ matrix.repo.name }}
          if [ -n "${{ matrix.repo.generator.config.target }}" ]; then
            mkdir -p $(dirname ${{ github.workspace }}/${{ matrix.repo.name }}/${{ matrix.repo.generator.config.target }})
            curl \
              -Lo ${{ github.workspace }}/${{ matrix.repo.name }}/${{ matrix.repo.generator.config.target }} \
              ${{ matrix.repo.generator.config.source }}
          fi
          # todo: pull from release
          curl -Lo ${{ github.workspace }}/manta_3.1.1_amd64.deb https://manta-ops.s3.amazonaws.com/deb/tmp/manta_3.1.1_amd64.deb
          reprepro -b ${{ github.workspace }}/${{ matrix.repo.name }}/ includedeb focal ${{ github.workspace }}/manta_3.1.1_amd64.deb
